### ISSUE TITLE
Reference proxy error

### ISSUE THREAD

**Issue by ghost** [XenocodeRCE/neo-ConfuserEx#11]
**Describe the bug**
When I trying to edit reference proxy mode to ftn, it calls error when confusing.

**To Reproduce**
1. Create config file.
2. Put in config file `<protection id="ref proxy">
	<argument name="mode" value="ftn" />
</protection>`
3. Save it
4. Run CLI with this config file

**Expected behavior**
Protects without error

**Screenshots**
![screenshot_2](https://user-images.githubusercontent.com/42004187/43709236-cf38b518-995b-11e8-9a7f-27d6e2b76f8b.png)

**Comment by XenocodeRCE** [comment]
Works fine with my file. Can you share yours ?

**Comment by XenocodeRCE** [comment]
Still no reply ? I close it 

Also : 

```
ftn: Neo ConfuserEx would use function pointer as proxy. Not implemented yet.
```

Don't expect to have working result when you use not implemented yet features.
