### ISSUE TITLE
The ObfuscationAttribute is not respected as it is respected by other obfuscators

### ISSUE THREAD

**Issue by steffen-liersch** [XenocodeRCE/neo-ConfuserEx#16]
The ObfuscationAttribute should be respected as it is respected by other obfuscators like Babel or Obfuscar.

If a class is tagged with [Obfuscation] the following items should not be renamed:

- the class itself
- the members of the class.

At the moment it seems as if ApplyToMembers is ignored. The default value of ApplyToMembers is true!

**Comment by XenocodeRCE** [comment]
We will follow ConfuserEx guideline on obfuscation attributes for the moment and we might change that
