### ISSUE TITLE
[Discussion] - Ideas

### ISSUE THREAD

**Issue by alexmurari** [XenocodeRCE/neo-ConfuserEx#2]
Hi, @XenocodeRCE.

Thanks for continuing ConfuserEx, no one else "really" continued it, but there are some cool ideas scattered around which I think might be useful, and, if all parties agreed, could be merged in one project.

Here are some links.

Protection plugins (type scramble, anti-watermark, fake-obfuscator, memory protection, may be more)
https://github.com/BahNahNah/ConfuserExPlugins
https://github.com/HoLLy-HaCKeR/Confuser.Protections.HoLLy

Project updates (.net core, bug fixes, etc..)
Pending pull requests - https://github.com/yck1509/ConfuserEx
modPhuserEx - https://github.com/0xFireball/ModPhuserEx
ConfuserEx Reborn - https://github.com/CubeCoders/ConfuserEx-Reborn
HoLLy-HaCKeR version - https://github.com/HoLLy-HaCKeR/ConfuserEx/
windpalme version - https://github.com/windpalme/ConfuserEx/

Thanks.

**Comment by LuanDevecchi** [comment]
It would be great to merge ConfuserEx Reborn changes and pending pull requests of original repo.

**Comment by XenocodeRCE** [comment]
@MurariAlex 

Hello :-)

- BahNahNah's TypeScramble need to be re-worked, public tools can clean it.
- I'll apply official ConfuserEx pull requests about fixes and net core, however i'm a Windows user and for me obfuscation only make sense on closed-source OS. I'll mainly develop features * for windows* 
-I'll check out all these ConfuserEx repos.

You all have to understand : since it is open-source, anyone can look at it and build a deobfuscator easily. That is what already happenned. I'll keep it open-source what happen.

My vision of this repo is more about shaping ideas into code.

**Comment by XenocodeRCE** [comment]
@MurariAlex after having passed a whole month on reading and looking for what you wrote, I came to that conclusion : 

| CUSTOM CONFUSEREX | LINK | COMMENT |
| ------ | ------ | ------ |
| ModPhuserEx  | https://github.com/0xFireball/ModPhuserEx | Add another compressor |
| ConfuserEx Reborn| https://github.com/CubeCoders/ConfuserEx-Reborn | Real core improvements |
| HoLLy-HaCKeR| https://github.com/HoLLy-HaCKeR/ConfuserEx/ | Minor stylistic changes |
| windpalme | https://github.com/windpalme/ConfuserEx/ | Useless changes on const value |

To that extent I'll merge pull requests from original repo and start the developpement of Neo-ConfuserEX

**Comment by alexmurari** [comment]
@XenocodeRCE Thanks for considering and studying this, really apprecitate it.
One suggestion though: update [dnlib](https://github.com/0xd4d/dnlib) to the latest version, the Yck's branch is really outdated, 0xd4d keeps updating dnlib and since all the assembly reading/writing process is made through it, I think it´s an important thing to do.

**Comment by XenocodeRCE** [comment]
@MurariAlex Yck's branch is different than the Master branch and uses new functions for the Import namespace etc. I'll stick to it. No major issue with that one 🍷

**Comment by XenocodeRCE** [comment]
@MurariAlex @LuanDevecchi I allow myself to close this, as it has been done by now 🍷
