### ISSUE TITLE
Exception: System.UriFormatException: Invalid URI: The format of the URI could not be determined.

### ISSUE THREAD

**Issue by TetteDev** [XenocodeRCE/neo-ConfuserEx#22]
**Describe the bug**
Encounter this error when trying to protect an exectuable.

**To Reproduce**
Calling the cli program like this

`var psi = new ProcessStartInfo(Path.Combine(Application.StartupPath, "Confuser.CLI.exe"))
						{
							Arguments = args,
							UseShellExecute = false,
							CreateNoWindow = false
						};
						Process.Start(psi);`

the arguments passed are
`-o <my outputpath> <filename of file I want to protect`
The exact arguments can be seen at the top of the screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/6103339/45908107-1154a100-bdfb-11e8-96e8-a47b11aac4c2.png)

Encountered the same issue with the non-fork version of confuser too

**Comment by hollow87** [comment]
Can confirm.

https://github.com/XenocodeRCE/neo-ConfuserEx/blob/3cd7d234150455a27a966ff528d379fa6d0f2281/Confuser.Core/ConfuserEngine.cs#L92

Causes `context.BaseDirectory` to become `\` which causes that exception as `\` is not a valid URI

**Comment by TetteDev** [comment]
Replacing line 92 with 

`context.BaseDirectory = Path.Combine(Environment.CurrentDirectory, parameters.Project.BaseDirectory.TrimEnd(Path.DirectorySeparatorChar) + "." + Path.DirectorySeparatorChar);` as user @hollow87  recommended fixed this issue!
