### ISSUE TITLE
Obfuscated property works differently

### ISSUE THREAD

**Issue by lcsondes** [XenocodeRCE/neo-ConfuserEx#24]
**Describe the bug**
I have a property that looks like `string MyProperty => (A && !B) ? "string A" : "string B";`. After obfuscation it is always returning `null`.

**To Reproduce**
I have tried to produce a minimal example, but it seems that this is specific to our particular project. If I do this in a test class it works.

Here's my config:
<details><summary>Configuration file</summary><p>

```xml
  <rule preset="none" pattern="true">
    <protection id="anti debug">
      <argument name="mode" value="safe" />
    </protection>
    <protection id="anti ildasm" />
    <protection id="constants">
      <argument name="mode" value="normal" />
      <argument name="elements" value="S" />
    </protection>
    <protection id="ctrl flow">
      <argument name="type" value="switch" />
    </protection>
    <protection id="rename">
      <argument name="mode" value="ascii" />
      <argument name="renPublic" value="false" />
    </protection>
    <protection id="resources">
      <argument name="mode" value="normal" />
    </protection>
  </rule>
```

</p></details>

<br>

**Expected behavior**
The property to behave the same way as it is unobfuscated.

**Screenshots**
N/A

**File (optional)**
N/A

**Additional context**
If I add `Trace.WriteLine` methods to the property getter, the problem goes away, as well as using `ObfuscationAttribute` on it to exclude it from obfuscation. I'm happy to help with debugging this but I've spent 2 days so far on this not really knowing where to even look really. The decompiled method looks like it's a funky `switch` that jumps around and eventually calls `<Module>.something<string>(number)` with two different numbers, so it vaguely looks like my original code. I didn't prove this due to the extreme difficulty in debugging (even with anti debug off and looking at the x64 disassembly, so in a way ConfuserEx works great :) ) but the only plausible explanation for me seems that these decryptor(?) methods are the ones returning `null`.

**Comment by lcsondes** [comment]
The problem persists if the only obfuscation I apply is
```
  <rule preset="none" pattern="true">
    <protection id="constants">
      <argument name="elements" value="S" />
    </protection>
  </rule>
```

The `ldstr` instruction is replaced by `ldc.i4`, a `br.s` to the next instruction, and a `call` to the decryptor method.

Changing the property to something like
```
var x = ternary_expression_from_above;
if(x == null)
  Debugger.Break();
return x;
```

Also makes the problem go away.

**Comment by XenocodeRCE** [comment]
Ternary operator are not handled, and without further exemple for me to test on (your app) i cannot fix.
