### ISSUE TITLE
Protected file crashes on Windows 7

### ISSUE THREAD

**Issue by xitska** [XenocodeRCE/neo-ConfuserEx#29]
**Describe the bug**
When running a protected file on Windows 7, it crashes.

**To Reproduce**
1. Protect a file
2. Run it on Windows 7
3. Witness a crash

**Expected behavior**
It is expected not to crash.

**Additional comments**
This may be due to the configuration or the program itself.

**Comment by mkaring** [comment]
Can you share the protections you did choose to use? And can you give some information regarding the application you are trying to protection. What technologies are used (e.g. WPF) and what framework version you are targeting?

Without any information it is not possible to track down the issue.

**Comment by XenocodeRCE** [comment]
Indeed. Share with us the config / program, my unit tests works fine. I'll push a commit today with new updates

**Comment by xitska** [comment]
Oh yes, sorry. It's a console program being protected with the maximum preset.
`<rule pattern="true" preset="maximum" inherit="false" />`
It's also running on .NET Framework 4.5.

**Comment by XenocodeRCE** [comment]
```
<project outputDir="C:\Users\¤¤¤\source\repos\neo-ConfuserEx\UnitTest\bin\Debug\Confused" baseDir="C:\Users\¤¤¤\source\repos\neo-ConfuserEx\UnitTest\bin\Debug" xmlns="http://confuser.codeplex.com">
  <module path="UnitTest.exe">
    <rule pattern="true" preset="maximum" inherit="false">
      <protection id="anti ildasm" />
      <protection id="anti tamper" />
      <protection id="constants" />
      <protection id="ctrl flow" />
      <protection id="anti dump" />
      <protection id="anti debug" />
      <protection id="ref proxy" />
      <protection id="resources" />
      <protection id="rename" />
    </rule>
  </module>
</project>
```

Works perfectly fine with the in-built unit test app 

[UnitTest.zip](https://github.com/XenocodeRCE/neo-ConfuserEx/files/2872997/UnitTest.zip)

**Comment by xitska** [comment]
Weird, my program works fine without protection but crashes with it.

**Comment by XenocodeRCE** [comment]
Since you seems to not be able to give further informations i'll close the thread. Come back when you will be able to give usefull informations about your program :-)
