### ISSUE TITLE
Missing some features

### ISSUE THREAD

**Issue by alexmurari** [XenocodeRCE/neo-ConfuserEx#3]
Hi, @XenocodeRCE !

You say on the readme that you have merged some pull requests from the original ConfuserEx branch and added an type scrambler, but I can´t find them at all on your branch.

Some pulls that can be merged:
https://github.com/yck1509/ConfuserEx/pull/591
https://github.com/yck1509/ConfuserEx/pull/561
https://github.com/yck1509/ConfuserEx/pull/553
https://github.com/yck1509/ConfuserEx/pull/462

Thanks.

Edit: Also I didn´t find anything about the constants encodign too.

**Comment by XenocodeRCE** [comment]
@MurariAlex Hello

Constant encoding changes has been made, You can see it [here](https://github.com/XenocodeRCE/neo-ConfuserEx/blob/master/Confuser.Runtime/Constant.cs#L44) and its pull request [here](https://github.com/XenocodeRCE/neo-ConfuserEx/pull/1)

As-of-today release [here](https://github.com/XenocodeRCE/neo-ConfuserEx/releases) already includes that typeScrambling features. I just pushed the commit, was an issue with Github Desktop 😭

**Comment by XenocodeRCE** [comment]
@MurariAlex 

I merged those PR, see latest [commits](https://github.com/XenocodeRCE/neo-ConfuserEx/commits?author=XenocodeRCE)

If you have other recommendations, let me know 🍷

**Comment by alexmurari** [comment]
@XenocodeRCE,

Thanks, looks good now.

That's all. Great job.
