### ISSUE TITLE
How to remove ConfuserEx signature ?

### ISSUE THREAD

**Issue by mridah** [XenocodeRCE/neo-ConfuserEx#32]
I have replaced all occurances of `ConfuserEx` from the project, but still hex editor shows `ConfuserEx v1.0.0-xxxxxx` signature somewhere in the ex, and decompilers re able to identify it's encrypted using ConfuserEx. How can I remove this signature ? @XenocodeRCE

**Comment by XenocodeRCE** [comment]
Hello,

Can you show me where it shows ConfuserEx v1.0.0-xxx... ?

**Comment by mridah** [comment]
Hi, 

Thanks for the fast reply :)
I've attached the screenshots of a Hex editor, showing the signature, and of a software `Exeinfo PE` which shows that the exe has been encrypted using ConfuserEx.  I've replaced ALL occurances of `ConfuserEx` in the entire solution. 

![confuserex_0](https://user-images.githubusercontent.com/21169606/53506009-17058f80-3adb-11e9-84a9-6fae6768f8f8.JPG)

![confuserex_1](https://user-images.githubusercontent.com/21169606/53506012-1a008000-3adb-11e9-99d8-c23cc6a92fda.JPG)

**Comment by XenocodeRCE** [comment]
Hello.

You need to remove the assembly builder info too : 

• https://github.com/XenocodeRCE/neo-ConfuserEx/blob/master/Build/UpdateVersion.cs
• https://github.com/XenocodeRCE/neo-ConfuserEx/blob/master/GlobalAssemblyInfo.Template.cs

**Comment by mkaring** [comment]
Maybe it looks for the watermark? I think it always writes the file signature of the ConfuserEx executable into the ConfusedBy attribute.

**Comment by mridah** [comment]
Thanks @XenocodeRCE , and @mkaring. It's working fine now :+1:
