### ISSUE TITLE
Cannot run in other computer but running fine in my computer. 

### ISSUE THREAD

**Issue by radiaku** [XenocodeRCE/neo-ConfuserEx#33]
**Describe the bug**
Cant run in other computer ( trying on 4 computer ) , Iam using gui version. But running fine in my computer ( no issue ). No error and nothing, just error. 

searching on other issue. https://github.com/XenocodeRCE/neo-ConfuserEx/issues/10 , but where is to disable TypeScrambler in GUI version? I cant find it. 

thanks you

**Comment by XenocodeRCE** [comment]
If its urning fine on *your* computer but not on *other* computers, the problem is located on the *other* computers.

Check if they have all needed libraries / dependencies, your program needs.

**Comment by radiaku** [comment]
@xenocodeRCE, the original file, run without problem in other 4 computers. But when I using neo confuse, its won't run... I don't what happen..

**Comment by radiaku** [comment]
Update: I using [mkaring ](https://github.com/mkaring/ConfuserEx)confuser , its works no problem on others computer? I think the problem is with TypeScrambler , But I cant disable it when using GUI.

**Comment by XenocodeRCE** [comment]
You can just remove it from the project. Since it's solved I'm closing the Issue :-)
