### ISSUE TITLE
Exception in WPF apps

### ISSUE THREAD

**Issue by Kaidoz** [XenocodeRCE/neo-ConfuserEx#35]
Protection 'types scrambler' in WPF apps
Error: Exception: 'System.Windows.Markup.XamlParseException' in PresentationFramework.dll
Screen: https://prnt.sc/n50hhw

File:
https://www.sendspace.com/file/1399zs

**Comment by XenocodeRCE** [comment]
I'm closing. Don't use Type Scrambler as it is bugged. Will need to remove that protection from repo.
