### ISSUE TITLE
Compressor causes console application to fail

### ISSUE THREAD

**Issue by mkaring** [XenocodeRCE/neo-ConfuserEx#4]
**Describe the bug**
The compressor causes an exception during the startup of a console application.

**To Reproduce**
1. Create a console application
2. Ensure that the prefer 32bit flag is set
3. Enable the compressor in ConfuserEx, only the confuser. Other obfuscations don't impact the behaviour of this bug.
4. Run the compressed assembly.

It will raise a Win32Exception, once it tries to read the modules of any 64 process on the system.

**Expected behavior**
No exception is raised.

**Additional context**
The exception is caused by the `CheckEnvironment` method that is in the Runtime for the compressor. I am not sure what the purpose of this method it, because it changes the behaviour of a console application by showing the main modules of every process on the system. Maybe this is a debugging left over?

**Comment by XenocodeRCE** [comment]
@mkaring please see latest commit [here](https://github.com/XenocodeRCE/neo-ConfuserEx/commit/427ed4d9e96513f699ca610c0377f6dd17abf768)
