### ISSUE TITLE
What version of dnlib do you need to build this? 

### ISSUE THREAD

**Issue by rollsch** [XenocodeRCE/neo-ConfuserEx#47]
**Describe the bug**
dnlib is not included. I cloned master dnlib but there are references to items that are no there.

**To Reproduce**
1. clone latest neo-confuserex
2. clone latest dnlib
3. attempt to build

> error CS0246: The type or namespace name 'IModuleWriterListener' could not be found (are you missing a using directive or an assembly reference?)
> error CS0246: The type or namespace name 'IModuleWriterListener' could not be found (are you missing a using directive or an assembly reference?)
> error CS0538: 'IModuleWriterListener' in explicit interface declaration is not an interface
> error CS0246: The type or namespace name 'IImageStream' could not be found (are you missing a using directive or an assembly reference?)
> error CS0246: The type or namespace name 'ImportResolver' could not be found (are you missing a using directive or an assembly reference?)
> error CS0115: 'InjectHelper.InjectContext.Resolve(TypeDef)': no suitable method found to override
> error CS0115: 'InjectHelper.InjectContext.Resolve(MethodDef)': no suitable method found to override
> error CS0115: 'InjectHelper.InjectContext.Resolve(FieldDef)': no suitable method found to override
> error CS0246: The type or namespace name 'IImageStream' could not be found (are you missing a using directive or an assembly reference?)

**Expected behavior**
Builds correctly.

Please put instructions on how to build, use nuget packages or include a copy of dnlib with your source.

**Comment by XenocodeRCE** [comment]
Hello, its a fork of ConfuserEx, which used a fork of dnlib. So naturally, it uses that fork of dnlib https://github.com/yck1509/dnlib/tree/532c767a9a4f6af51cd4eb5d1c0af750c8509c5d

**Comment by rollsch** [comment]
Thank you.
