### ISSUE TITLE
Building the Project the first time

### ISSUE THREAD

**Issue by cherbin** [XenocodeRCE/neo-ConfuserEx#60]
**Describe the bug**

The dnlib (unavailable) The project file or web cannot be found.

What do I need to do to compile ?

**To Reproduce**

**Expected behavior**

**Screenshots**

**File (optional)**
Either share a link to download the file or e-mail it to me.

**Additional context**

**Comment by zsr2531** [comment]
Clone using `git clone --recursive https://github.com/XenocodeRCE/neo-ConfuserEx.git`

**Comment by XenocodeRCE** [comment]
https://github.com/yck1509/dnlib/tree/532c767a9a4f6af51cd4eb5d1c0af750c8509c5d this is the dnlib src used in this repo.
