### ISSUE TITLE
Additional Methods Added During Name Protection?

### ISSUE THREAD

**Issue by g3v0** [XenocodeRCE/neo-ConfuserEx#62]
Hi, I noticed some additional methods and fields being added in blank namespace after Name Protection. I've looked through the source code but I couldn't figure out where or why they're being added. Any ideas?

![ConfuserEx_Problem](https://user-images.githubusercontent.com/3489521/78371119-60e16480-757c-11ea-9cc5-b30367c6ffd2.PNG)

Screenshot is from dnSpy after using Name Protection only (debug setting). I'm wondering where those `<>f__AnonymousType0<\u0001,\u0002>` and `<PrivateImplemenationDetails>` methods come from.

**Comment by ElektroKill** [comment]
These types are generated by the compiler, they are most likely used by string switches, array initializers, and other things. Don’t worry about them.
