### ISSUE TITLE
Reference Proxy fails

### ISSUE THREAD

**Issue by ghost** [XenocodeRCE/neo-ConfuserEx#9]
**Describe the bug**
When I trying to edit reference proxy mode to strong, it calls error in protected application.

**To Reproduce**
1. Create config file.
2. Put in config file `<protection id="ref proxy">
	<argument name="mode" value="strong" />
</protection>`
3. Save it
4. Run CLI with this config file
5. Try to run application

**Expected behavior**
Application works normally

**Screenshots**
![screenshot_3](https://user-images.githubusercontent.com/42004187/43596396-e49d8036-9687-11e8-80c0-351e9136aeb9.png)

**Comment by XenocodeRCE** [comment]
You did not follow bug report template.  I'll run tests on my own and let you know

**Comment by ghost** [comment]
Rewrite by template

**Comment by ghost** [comment]
Bug not in reference proxy, I try to set default r.p. but it crushes again

**Comment by ghost** [comment]
You didnt understand me. I have replaced to default ConfuserEx Reference Proxy, it continue crashes, but in default confuser with this settings it doesnt crash.
